=== eudiko/wsd-lab4/creatorsupport.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT creators (creator+)>
<!ELEMENT creator (creator-id, creator-name, bio, projects)>
<!ELEMENT creator-id (#PCDATA)>
<!ELEMENT creator-name (#PCDATA)>

<!ELEMENT projects (project+)>
<!ELEMENT project (project-name, funding-goal)>
<!ELEMENT project-name (#PCDATA)>
<!ELEMENT funding-goal (#PCDATA)>

<!ATTLIST creator id ID #REQUIRED>
<!ATTLIST project id ID #REQUIRED>

=== eudiko/wsd-lab4/creatorsupport.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="creatorsupport.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<!-- <!DOCTYPE creators SYSTEM "creatorsupport.dtd"> -->
<?xml-stylesheet type="text/xsl" href="transform.xsl"?>

<creators xmlns="www.abc.com/creator-support">
    <creator id="C1">
        <creator-id>1</creator-id>
        <creator-name>Jon Doeson</creator-name>
        <projects>
            <project>
                <project-name>Animated Short Film</project-name>
                <funding-goal>250000</funding-goal>
            </project>
        </projects>
    </creator>
    <creator id="C2">
        <creator-id>2</creator-id>
        <creator-name>Jane Smiths</creator-name>
        <projects>
            <project>
                <project-name>Coding Project Repository</project-name>
                <funding-goal>30000</funding-goal>
            </project>
        </projects>
    </creator>
    <creator id="C3">
        <creator-id>3</creator-id>
        <creator-name>Jo Joseph</creator-name>
        <projects>
            <project>
                <project-name>Fighting Game</project-name>
                <funding-goal>300000</funding-goal>
            </project>
        </projects>
    </creator>
    <creator id="C4">
        <creator-id>4</creator-id>
        <creator-name>Michael Reef</creator-name>
        <projects>
            <project>
                <project-name>Engineering Workshop</project-name>
                <funding-goal>50000</funding-goal>
            </project>
        </projects>
    </creator>
</creators>
